mode: conditional
seed: 3556396155
num_loci: 100000
structured_interval:
  duration: 2.0
  configuration: '1010'
  migration:
    m01: 0.0
    m10: 0.0
  coalescence:
    lambda0: 1.0
    lambda1: 1.0
output:
  directory: simulations/quartet/datasets/raw/conditional_grid/d06_m00
  record_resolved_config: true
